app:
    host: "localhost"
    port: 2020
    name: "apiDoc-go"

mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "root"
    charset: "utf8mb4"
    dbName: "api-doc"

log:
    path: "runtime/log"

redis:
    host: "127.0.0.1"
    port: 6379
    user: ""
    password: ""
    dbId: 0
